In [5]:
# 1-1
import numpy as np
import pandas as pd
df=pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/data/main/exam/9_1_1.csv')
print(df.info())
print(df.head())

df['합계']=df['금액1']+df['금액2']
df1=df.groupby(['year', '지역코드', 'gender'])['합계'].sum().reset_index()
df1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    100 non-null    int64
 1   gender  100 non-null    int64
 2   지역코드    100 non-null    int64
 3   금액1     100 non-null    int64
 4   금액2     100 non-null    int64
dtypes: int64(5)
memory usage: 4.0 KB
None
   year  gender  지역코드    금액1    금액2
0  2018       0   143  70713  43210
1  2019       0   183  40306  39663
2  2017       0   129  26646  41631
3  2019       0   161  56843  12455
4  2019       0   174  26371   9014

    year  지역코드  gender      합계
0   2015   101       1   87088
1   2015   118       1  100609
2   2015   130       1   41599
3   2015   131       0   37881
4   2015   150       1   56775
..   ...   ...     ...     ...
89  2020   176       0   85767
90  2020   178       0   71066
91  2020   192       1  109436
92  2020   195       1   34792
93  2020   196       0   76900

[94 rows x 4 columns]

In [20]:
# 1-2
import numpy as np
import pandas as pd
df=pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/data/main/exam/9_1_2.csv')
print(df.info())
print(df.head())

df1=df[df['구분']=='발생건수'].drop(columns=['구분']).set_index('연도')
df2=df[df['구분']=='검거건수'].drop(columns=['구분']).set_index('연도')
df3=df2/df1
df3
# def check(x):
#     x == x.max
# df3.apply(check)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   연도      50 non-null     int64
 1   구분      50 non-null     object
 2   범죄유형1   50 non-null     int64
 3   범죄유형2   50 non-null     int64
 4   범죄유형3   50 non-null     int64
 5   범죄유형4   50 non-null     int64
 6   범죄유형5   50 non-null     int64
 7   범죄유형6   50 non-null     int64
 8   범죄유형7   50 non-null     int64
 9   범죄유형8   50 non-null     int64
 10  범죄유형9   50 non-null     int64
 11  범죄유형10  50 non-null     int64
dtypes: int64(11), object(1)
memory usage: 4.8+ KB
None
     연도    구분  범죄유형1  범죄유형2  범죄유형3  범죄유형4  범죄유형5  범죄유형6  범죄유형7  범죄유형8  범죄유형9  \
0  2000  발생건수    302    635    470    306    271    900    220    814    321
1  2000  검거건수    302    430    470    187    271    199    220    230    321
2  2001  발생건수    969    543    691    613    585    391    476    360    659
3  2001  검거건수    121    352    691    613    574    158    476    360    575
4  2002  발생건수    982    389    886    762    766    443    704    330    684

   범죄유형10
0     666
1     408
2     513
3     513
4     846

,범죄유형1,범죄유형2,범죄유형3,범죄유형4,범죄유형5,범죄유형6,범죄유형7,범죄유형8,범죄유형9,범죄유형10
연도,,,,,,,,,,
2000,1.000000,0.677165,1.000000,0.611111,1.000000,0.221111,1.000000,0.282555,1.000000,0.612613
2001,0.124871,0.648250,1.000000,1.000000,0.981197,0.404092,1.000000,1.000000,0.872534,1.000000
2002,0.122200,0.683805,0.420993,0.639108,0.913838,0.936795,0.160511,1.000000,1.000000,0.526005
2003,0.235602,1.000000,1.000000,0.178445,0.747706,1.000000,0.289548,0.893333,1.000000,1.000000
2004,0.584027,0.862217,0.523179,1.000000,1.000000,1.000000,0.929787,0.232061,1.000000,0.341253
2005,0.236760,1.000000,0.986183,0.234104,0.991667,1.000000,1.000000,1.000000,1.000000,0.953959
2006,0.270492,0.254325,0.619342,0.734398,1.000000,1.000000,0.872247,1.000000,1.000000,0.659857
2007,0.953092,0.605911,0.462935,0.135392,0.674587,1.000000,1.000000,0.960114,0.871636,0.569514
2008,0.176933,1.000000,0.277599,1.000000,0.564356,0.430233,0.944093,0.792740,1.000000,0.886486
2009,0.782665,0.528994,0.574874,1.000000,0.352869,0.429139,0.897959,0.477432,0.720755,0.872467
2010,0.391778,0.352754,1.000000,1.000000,0.520352,1.000000,1.000000,0.673349,0.642166,0.902968
2011,1.000000,0.258621,1.000000,0.277851,0.216274,1.000000,0.545299,1.000000,1.000000,0.399015
2012,0.592466,0.893688,0.360812,0.860182,0.880952,0.566251,0.932185,0.451206,0.416942,1.000000
2013,1.000000,1.000000,0.798107,1.000000,0.621287,1.000000,1.000000,0.637306,0.470476,1.000000
2014,1.000000,0.431466,1.000000,0.452514,0.529762,0.739264,0.998512,0.288571,0.656352,0.710262
2015,0.591069,0.384969,0.648305,0.610028,1.000000,1.000000,1.000000,0.843823,1.000000,1.000000
2016,0.864686,1.000000,1.000000,0.836013,0.957687,0.739583,1.000000,1.000000,0.914339,0.258564
2017,1.000000,0.228333,0.392133,1.000000,0.746336,0.814871,1.000000,0.665505,0.570136,0.342466
2018,0.310924,0.612839,0.143564,0.561077,0.469118,0.394172,0.671329,0.202797,0.632708,1.000000
2019,1.000000,0.227754,1.000000,0.734864,0.474453,0.510057,0.842315,0.597368,0.145161,1.000000
2020,0.271949,0.769935,0.630689,1.000000,0.229379,0.496468,0.418182,0.564682,0.160093,0.687351
2021,0.993190,0.637787,0.677069,1.000000,0.787293,0.343262,0.812766,0.512443,1.000000,1.000000
2022,1.000000,0.915509,0.870680,1.000000,0.393316,1.000000,1.000000,0.707602,0.197659,1.000000
2023,0.897436,1.000000,1.000000,1.000000,0.776978,0.398907,1.000000,0.822222,0.335470,0.782074
2024,0.904255,0.289747,1.000000,0.219192,1.000000,1.000000,0.698810,1.000000,0.445378,0.404494

In [19]:
# 1-3
import numpy as np
import pandas as pd
df=pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/data/main/exam/9_1_3.csv')
print(df.info())
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   부서      100 non-null    object
 1   등급      100 non-null    object
 2   평균만족도   90 non-null     float64
 3   근속연수    90 non-null     float64
 4   교육참가횟수  100 non-null    float64
dtypes: float64(3), object(2)
memory usage: 4.0+ KB
None
          부서 등급     평균만족도  근속연수  교육참가횟수
0    Finance  C  4.023911  17.0     8.0
1  Marketing  A  3.756698  14.0    16.0
2         IT  B  2.628697  21.0    13.0
3  Marketing  A  3.196616   NaN    18.0
4  Marketing  C  4.770665  28.0    10.0